"""
Aggregate spectral probing metrics and report regression slopes.

This script scans metrics JSON files generated by `run_generic_fft_band_probe.py`,
fits linear trends over per-band accuracy curves, and exports summary artifacts:
- overall_genre_trends.json
- overall_genre_trends.csv
- overall_genre_trends.png
"""

import argparse
import csv
import json
import math
from pathlib import Path

import numpy as np  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Aggregate per-target spectral metrics into global trend stats."
    )
    parser.add_argument(
        "--metrics_glob",
        type=str,
        default="results/**/*_spectral_summary_*_metrics.json",
        help="Recursive glob for spectral metrics JSON files.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="results/2nd_exp",
        help="Output directory for aggregated trend artifacts.",
    )
    parser.add_argument(
        "--min_points",
        type=int,
        default=3,
        help="Minimum number of datapoints required to fit regression.",
    )
    return parser.parse_args()


def _fit_line(x: np.ndarray, y: np.ndarray) -> dict[str, float]:
    slope, intercept = np.polyfit(x, y, deg=1)
    y_pred = slope * x + intercept
    ss_res = float(np.sum((y - y_pred) ** 2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))
    r2 = 1.0 - (ss_res / ss_tot) if ss_tot > 0 else float("nan")
    return {
        "slope": float(slope),
        "intercept": float(intercept),
        "r2": float(r2),
    }


def _curve_record(
    task: str,
    genre: str,
    transform_type: str,
    method: str,
    values: list[float],
    min_points: int,
) -> dict:
    rec = {
        "task": task,
        "genre": genre,
        "transform_type": transform_type,
        "method": method,
        "n_points": int(len(values)),
        "values": [float(v) for v in values],
        "slope": None,
        "intercept": None,
        "r2": None,
        "valid_for_regression": False,
    }
    if len(values) >= min_points:
        x = np.arange(len(values), dtype=np.float64)
        y = np.asarray(values, dtype=np.float64)
        fit = _fit_line(x, y)
        rec.update(fit)
        rec["valid_for_regression"] = True
    return rec


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    paths = sorted(Path(".").glob(args.metrics_glob))
    if not paths:
        raise FileNotFoundError(
            f"No metrics files matched --metrics_glob='{args.metrics_glob}'."
        )

    records: list[dict] = []
    for path in paths:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)

        target = str(data.get("target_label", path.stem))
        label_key = str(data.get("label_key", "label"))
        transform_type = str(data.get("transform_type", "unknown"))
        accuracies = data.get("accuracies", {})
        task = label_key

        band_values = accuracies.get("band_specific", []) or []
        cumulative_values = accuracies.get("cumulative_per_band", []) or []

        records.append(
            _curve_record(
                task=task,
                genre=target,
                transform_type=transform_type,
                method="band_specific",
                values=band_values,
                min_points=args.min_points,
            )
        )
        records.append(
            _curve_record(
                task=task,
                genre=target,
                transform_type=transform_type,
                method="cumulative_per_band",
                values=cumulative_values,
                min_points=args.min_points,
            )
        )

    valid = [r for r in records if r["valid_for_regression"]]
    if not valid:
        raise RuntimeError(
            "No curves had enough points for regression. "
            f"Try lowering --min_points (current: {args.min_points})."
        )

    slopes = np.asarray([float(r["slope"]) for r in valid], dtype=np.float64)
    pos_ratio = float(np.mean(slopes > 0))
    neg_ratio = float(np.mean(slopes < 0))

    # Group summaries by (task, method, transform_type).
    grouped: dict[tuple[str, str, str], list[float]] = {}
    for r in valid:
        key = (r["task"], r["method"], r["transform_type"])
        grouped.setdefault(key, []).append(float(r["slope"]))

    grouped_summary = []
    for (task, method, transform_type), vals in sorted(grouped.items()):
        arr = np.asarray(vals, dtype=np.float64)
        grouped_summary.append(
            {
                "task": task,
                "method": method,
                "transform_type": transform_type,
                "count": int(arr.size),
                "slope_mean": float(np.mean(arr)),
                "slope_std": float(np.std(arr)),
                "slope_min": float(np.min(arr)),
                "slope_max": float(np.max(arr)),
                "positive_ratio": float(np.mean(arr > 0)),
            }
        )

    # Outliers by absolute slope.
    outliers = sorted(valid, key=lambda r: abs(float(r["slope"])), reverse=True)[:20]

    payload = {
        "config": {
            "metrics_glob": args.metrics_glob,
            "output_dir": str(output_dir),
            "min_points": int(args.min_points),
            "num_metrics_files": int(len(paths)),
            "num_curve_records": int(len(records)),
            "num_valid_regressions": int(len(valid)),
        },
        "overall": {
            "slope_mean": float(np.mean(slopes)),
            "slope_std": float(np.std(slopes)),
            "positive_slope_ratio": pos_ratio,
            "negative_slope_ratio": neg_ratio,
        },
        "grouped_summary": grouped_summary,
        "per_curve": valid,
        "top_abs_slope_outliers": outliers,
    }

    json_path = output_dir / "overall_genre_trends.json"
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)

    csv_path = output_dir / "overall_genre_trends.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "task",
                "genre",
                "transform_type",
                "method",
                "n_points",
                "slope",
                "intercept",
                "r2",
            ]
        )
        for r in valid:
            writer.writerow(
                [
                    r["task"],
                    r["genre"],
                    r["transform_type"],
                    r["method"],
                    r["n_points"],
                    r["slope"],
                    r["intercept"],
                    r["r2"],
                ]
            )

    png_path = output_dir / "overall_genre_trends.png"
    plot_written = False
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt  # noqa: WPS433

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
        ax1.hist(
            slopes,
            bins=min(20, max(8, int(math.sqrt(len(slopes)) + 1))),
            color="steelblue",
            alpha=0.8,
        )
        ax1.axvline(
            np.mean(slopes),
            color="black",
            linestyle="--",
            linewidth=1,
            label=f"mean={np.mean(slopes):.4f}",
        )
        ax1.set_title("Slope Distribution")
        ax1.set_xlabel("Regression slope")
        ax1.set_ylabel("Count")
        ax1.legend(loc="best", fontsize=8)

        bar_labels = [
            f"{g['task']}|{g['method']}|{g['transform_type']}" for g in grouped_summary
        ]
        bar_vals = [g["slope_mean"] for g in grouped_summary]
        bar_err = [g["slope_std"] for g in grouped_summary]
        x = np.arange(len(bar_labels))
        ax2.bar(
            x,
            bar_vals,
            yerr=bar_err,
            color="mediumpurple",
            alpha=0.85,
            capsize=3,
        )
        ax2.axhline(0.0, color="black", linewidth=1)
        ax2.set_xticks(x)
        ax2.set_xticklabels(bar_labels, rotation=60, ha="right", fontsize=8)
        ax2.set_ylabel("Mean slope")
        ax2.set_title("Mean Slope by Task/Method/Transform")

        fig.tight_layout()
        fig.savefig(png_path)
        plt.close(fig)
        plot_written = True
    except ModuleNotFoundError:
        pass

    print(f"[aggregate_spectral_trends] Metrics files: {len(paths)}")
    print(f"[aggregate_spectral_trends] Valid regressions: {len(valid)}")
    print(f"[aggregate_spectral_trends] Saved JSON: {json_path}")
    print(f"[aggregate_spectral_trends] Saved CSV:  {csv_path}")
    if plot_written:
        print(f"[aggregate_spectral_trends] Saved PNG:  {png_path}")
    else:
        print(
            "[aggregate_spectral_trends] matplotlib not installed; "
            "skipped PNG export."
        )


if __name__ == "__main__":
    main()

